//
//  SmellTypeMarkdownBuilder.swift
//  ASTAnalyzer
//
//  Created on 2025-12-14.
//

import Foundation

/// Builder for creating smell type Markdown content
public final class SmellTypeMarkdownBuilder {

    private let formatter: MarkdownFormatter

    public init(formatter: MarkdownFormatter) {
        self.formatter = formatter
    }

    /// Creates Markdown content for a specific smell type
    /// - Parameters:
    ///   - smellType: The type of smell to document
    ///   - instances: The instances of this smell type
    ///   - report: The complete smell report for metadata
    /// - Returns: Formatted Markdown string
    public func buildSmellTypeMarkdown(smellType: DefectType, instances: [SmellInstance], report: SmellReport) -> String {
        var markdown = """
# \(smellType.rawValue)

**\(formatter.getSmellTypeDescription(smellType))**

## Summary

- **Total Instances**: \(instances.count)
- **Analysis Date**: \(report.metadata.timestamp.formatted(date: .abbreviated, time: .shortened))
- **Analysis Duration**: \(String(format: "%.3fs", report.metadata.duration))

## Instances

"""

        for (index, instance) in instances.enumerated() {
            markdown += formatInstance(index: index, instance: instance)
        }

        markdown += """

---

*Generated by AST Analyzer on \(report.metadata.timestamp.formatted(date: .complete, time: .complete))*
"""

        return markdown
    }

    private func formatInstance(index: Int, instance: SmellInstance) -> String {
        var result = """

### \(index + 1). \(instance.element.displayName)

**Severity**: \(instance.severityDescription) (\(String(format: "%.2f", instance.severity)))
**Location**: `\(instance.location.filePath):\(instance.location.lineNumber ?? 0)`

**Issue**: \(instance.message)

**Suggestion**: \(instance.suggestion)

"""
        if let context = instance.location.context {
            result += "**Context**: \(context)\n\n"
        }
        return result
    }
}