//
//  SummaryMarkdownBuilder.swift
//  ASTAnalyzer
//
//  Created on 2025-12-14.
//

import Foundation

/// Builder for creating summary Markdown content
public final class SummaryMarkdownBuilder {

    private let formatter: MarkdownFormatter

    public init(formatter: MarkdownFormatter) {
        self.formatter = formatter
    }

    /// Creates complete summary Markdown content
    /// - Parameter report: The smell report to summarize
    /// - Returns: Formatted Markdown string
    public func buildSummaryMarkdown(report: SmellReport) -> String {
        var markdown = buildSummaryHeader(report: report)
        markdown += buildHealthStatusMessage(report)
        markdown += buildCriticalIssuesSection(report)
        markdown += buildSmellsByTypeSection(report)
        markdown += buildRecommendationsSection(report)
        markdown += buildAnalysisMetadataSection(report)
        return markdown
    }

    private func buildSummaryHeader(report: SmellReport) -> String {
        """
# Architectural Analysis Report

**Analysis Summary**

| Metric | Value |
|--------|-------|
| Total Smells | \(report.totalSmells) |
| Health Score | \(report.healthScorePercentage) |
| Health Status | \(report.healthStatus) |
| Critical Issues | \(report.criticalSmells.count) |
| Files Analyzed | \(report.metadata.filesAnalyzed) |
| Classes Analyzed | \(report.metadata.classesAnalyzed) |
| Methods Analyzed | \(report.metadata.methodsAnalyzed) |
| Analysis Duration | \(String(format: "%.3fs", report.metadata.duration)) |

"""
    }

    private func buildHealthStatusMessage(_ report: SmellReport) -> String {
        if report.requiresRefactoring {
            "**⚠️ This codebase requires refactoring attention.**\n\n"
        } else {
            "**✅ This codebase is in good health.**\n\n"
        }
    }

    private func buildCriticalIssuesSection(_ report: SmellReport) -> String {
        guard !report.criticalSmells.isEmpty else { return "" }

        var section = "## 🚨 Critical Issues\n\n"
        for (index, smell) in report.criticalSmells.enumerated() {
            section += """
### \(index + 1). \(smell.element.displayName)

- **Type**: \(smell.type.rawValue)
- **Location**: `\(smell.location.filePath):\(smell.location.lineNumber ?? 0)`
- **Issue**: \(smell.message)
- **Suggestion**: \(smell.suggestion)

"""
        }
        return section
    }

    private func buildSmellsByTypeSection(_ report: SmellReport) -> String {
        var section = "## 📊 Smells by Type\n\n"
        section += "| Smell Type | Count | Description |\n"
        section += "|------------|-------|-------------|\n"

        for (type, count) in report.smellsByType.sorted(by: { $0.value > $1.value }) {
            let description = formatter.getSmellTypeDescription(type)
            section += "| \(type.rawValue) | \(count) | \(description) |\n"
        }
        section += "\n"
        return section
    }

    private func buildRecommendationsSection(_ report: SmellReport) -> String {
        guard !report.recommendations.isEmpty else { return "" }

        var section = "## 💡 Recommendations\n\n"
        for recommendation in report.recommendations {
            section += "- \(recommendation)\n"
        }
        section += "\n"
        return section
    }

    private func buildAnalysisMetadataSection(_ report: SmellReport) -> String {
        let timestamp = report.metadata.timestamp
        return """

## 📋 Analysis Metadata

- **Timestamp**: \(timestamp.formatted(date: .complete, time: .complete))
- **Version**: \(report.metadata.version)
- **Thresholds Used**:
  - God Class LOC: \(report.metadata.thresholds.classSmells.godClassLOC)
  - Long Method LOC: \(report.metadata.thresholds.methodSmells.longMethodLOC)
  - Lazy Class Methods: \(report.metadata.thresholds.classSmells.lazyClassNOM)
  - Lazy Class Fields: \(report.metadata.thresholds.classSmells.lazyClassNOF)
  - Deficient Encapsulation WOA: \(String(format: "%.2f", report.metadata.thresholds.classSmells.deficientEncapsulationWOA))
  - Multifaceted Abstraction LCOM: \(String(format: "%.2f", report.metadata.thresholds.classSmells.mfaLCOM))

---

*Generated by AST Analyzer - Advanced Swift Code Quality Analysis Tool*
"""
    }
}